networks:
  default:
    name: goproxy
    driver: bridge

services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
        
  plan-postgres:
    image: postgres:17.2-bookworm
    container_name: plan-postgres
    environment:
      POSTGRES_USER: ${PLANS_DB_USER}
      POSTGRES_PASSWORD: ${PLANS_DB_PASS}
      POSTGRES_DB: ${PLANS_DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - plan-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  billing-postgres:
    image: postgres:17.2-bookworm
    container_name: lavatop-billing-postgres
    environment:
      POSTGRES_USER: ${BILLING_DB_USER}
      POSTGRES_PASSWORD: ${BILLING_DB_PASS}
      POSTGRES_DB: ${BILLING_DB_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - billing-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-ctx-migrator:
    build:
      context: ./src
    container_name: auth-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  plans-ctx-migrator:
    build:
      context: ./src
    container_name: plans-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${PLANS_DB_DATABASE}
      - DB_USER=${PLANS_DB_USER}
      - DB_PASS=${PLANS_DB_PASS}
      - DB_HOST=${PLANS_DB_HOST}
      - DB_PORT=${PLANS_DB_PORT}
    depends_on:
      plan-postgres:
        condition: service_healthy

  billing-ctx-migrator:
    build:
      context: ./src
    container_name: billing-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${BILLING_DB_DATABASE}
      - DB_USER=${BILLING_DB_USER}
      - DB_PASS=${BILLING_DB_PASS}
      - DB_HOST=${BILLING_DB_HOST}
      - DB_PORT=${BILLING_DB_PORT}
    depends_on:
      billing-postgres:
        condition: service_healthy
  
  google-auth-api:
    build:
      context: ./src
    container_name: google-auth-api
    ports:
      - "3030:3030"
    environment:
      - MODE=google-auth
      - SERVE_PORT=3030
      - ALLOWED_ORIGINS=http://localhost:5173
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ENVIRONMENT=development
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
      - GOOGLE_AUTH_HOST=${GOOGLE_AUTH_HOST}
      - GOOGLE_AUTH_PORT=${GOOGLE_AUTH_PORT}
      - PROXY_KAFKA_AUTO_OFFSET_RESET=${PROXY_KAFKA_AUTO_OFFSET_RESET}
      - PROXY_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROXY_KAFKA_GROUP_ID=GOOGLE-AUTH
      - PROXY_KAFKA_TOPIC=PROXY
      - TC_CACHE_HOST=${TC_CACHE_HOST}
      - TC_CACHE_PORT=${TC_CACHE_PORT}
      - TC_CACHE_USER=${TC_CACHE_USER}
    depends_on:
      postgres:
        condition: service_healthy
      plan-controller-cache:
        condition: service_healthy
        
  proxy:
    build:
      context: ./src
    container_name: proxy
    ports:
      - "8888:8888"
    environment:
      - MODE=proxy
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - HTTP_LISTENER_PORT=8888
      - PROXY_KAFKA_TOPIC=${PROXY_KAFKA_TOPIC}
      - PROXY_KAFKA_AUTO_OFFSET_RESET=earliest
      - PROXY_KAFKA_GROUP_ID=traffic-processor
      - PROXY_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROXY_KAFKA_TOPIC=${PROXY_KAFKA_TOPIC}
      - TC_CACHE_HOST=${TC_CACHE_HOST}
      - TC_CACHE_PORT=${TC_CACHE_PORT}
      - TC_CACHE_USER=${TC_CACHE_USER}
      - TC_CACHE_PASSWORD=${TC_CACHE_PASSWORD}
    depends_on:
      init-kafka-topics:
          condition: service_completed_successfully
      auth-ctx-migrator:
        condition: service_completed_successfully

  rest-api:
    build:
      context: ./src
    container_name: rest-api
    ports:
      - "80:80"
    environment:
      - MODE=rest-api
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - HTTP_REST_API_PORT=80
      - PROXY_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROXY_KAFKA_GROUP_ID=${USERS_REST_API_KAFKA_GROUP_ID}
      - PROXY_KAFKA_AUTO_OFFSET_RESET=${PROXY_KAFKA_AUTO_OFFSET_RESET}
      - PROXY_KAFKA_TOPIC=${USERS_REST_API_KAFKA_TOPIC} 
      - ALLOWED_ORIGINS=*
    depends_on:
      - auth-ctx-migrator

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka-topics:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic PROXY --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic PLAN --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic BILLING --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      
      exit 0
      "

  kafka-relay:
    build:
      context: ./src
    container_name: kafka-relay
    environment:
      - MODE=kafka-relay
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - kafka

  plan-controller-cache:
    image: valkey/valkey:8.0-bookworm
    container_name: plan-controller-cache
    ports:
      - "6379:6379"
    volumes:
      - plan-controller-cache_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  plan-controller:
    build:
      context: ./src
    container_name: plan-controller
    ports:
      - "3031:3031"
    environment:
      - MODE=plan-controller
      - USERS_API_HOST=http://rest-api:80
      - DB_USER=${PLANS_DB_USER}
      - DB_PASS=${PLANS_DB_PASS}
      - DB_HOST=${PLANS_DB_HOST}
      - DB_PORT=${PLANS_DB_PORT}
      - DB_DATABASE=${PLANS_DB_DATABASE}
      - PROXY_KAFKA_TOPIC=${PROXY_KAFKA_TOPIC}
      - PLAN_KAFKA_TOPIC=${PLAN_KAFKA_TOPIC}
      - PLAN_KAFKA_AUTO_OFFSET_RESET=earliest
      - PLAN_KAFKA_GROUP_ID=traffic-processor
      - PLAN_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROXY_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROXY_KAFKA_GROUP_ID=${PROXY_KAFKA_GROUP_ID}
      - PROXY_KAFKA_AUTO_OFFSET_RESET=${PROXY_KAFKA_AUTO_OFFSET_RESET}
      - PROXY_KAFKA_TOPIC=${PROXY_KAFKA_TOPIC}
      - TC_CACHE_HOST=${TC_CACHE_HOST}
      - TC_CACHE_PORT=${TC_CACHE_PORT}
      - TC_CACHE_USER=${TC_CACHE_USER}
      - TC_CACHE_PASSWORD=${TC_CACHE_PASSWORD}
      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      init-kafka-topics:
        condition: service_completed_successfully
      plan-postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      plan-controller-cache:
        condition: service_healthy

volumes:
  postgres_data:
  plan-postgres_data: 
  billing-postgres_data:
  plan-controller-cache_data:
