networks:
  default:
    name: goproxy
    driver: bridge

services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tc-postgres:
    image: postgres:17.2-bookworm
    container_name: tc-postgres
    environment:
      POSTGRES_USER: ${TC_DB_USER}
      POSTGRES_PASSWORD: ${TC_DB_PASS}
      POSTGRES_DB: ${TC_DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - tc-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
        
  plans-postgres:
    image: postgres:17.2-bookworm
    container_name: plans-postgres
    environment:
      POSTGRES_USER: ${PLANS_DB_USER}
      POSTGRES_PASSWORD: ${PLANS_DB_PASS}
      POSTGRES_DB: ${PLANS_DB_DATABASE}
    ports:
      - "5434:5432"
    volumes:
      - plans-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-ctx-migrator:
    build:
      context: ./src
    container_name: auth-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      postgres:
        condition: service_healthy
          
  traffic-ctx-migrator:
    build:
      context: ./src
    container_name: traffic-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${TC_DB_DATABASE}
      - DB_USER=${TC_DB_USER}
      - DB_PASS=${TC_DB_PASS}
      - DB_HOST=${TC_DB_HOST}
      - DB_PORT=${TC_DB_PORT}
    depends_on:
      tc-postgres:
        condition: service_healthy
  
  plans-ctx-migrator:
    build:
      context: ./src
    container_name: plans-ctx-migrator
    environment:
      - MODE=migrator
      - DB_DATABASE=${PLANS_DB_DATABASE}
      - DB_USER=${PLANS_DB_USER}
      - DB_PASS=${PLANS_DB_PASS}
      - DB_HOST=${PLANS_DB_HOST}
      - DB_PORT=${PLANS_DB_PORT}
    depends_on:
      plans-postgres:
        condition: service_healthy
        
  proxy:
    build:
      context: ./src
    container_name: proxy
    ports:
      - "8888:8888"
    environment:
      - MODE=proxy
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - HTTP_LISTENER_PORT=8888
      - TC_KAFKA_TOPIC=${TC_KAFKA_TOPIC}
      - TC_KAFKA_AUTO_OFFSET_RESET=earliest
      - TC_KAFKA_GROUP_ID=traffic-processor
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - auth-ctx-migrator

  rest-api:
    build:
      context: ./src
    container_name: rest-api
    ports:
      - "80:80"
    environment:
      - MODE=rest-api
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - HTTP_REST_API_PORT=80
    depends_on:
      - auth-ctx-migrator

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka-topics:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic user-traffic --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  kafka-relay:
    build:
      context: ./src
    container_name: kafka-relay
    environment:
      - MODE=kafka-relay
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - kafka

  traffic-collector-cache:
    image: valkey/valkey:8.0-bookworm
    container_name: traffic-collector-cache
    ports:
      - "6379:6379"
    volumes:
      - traffic-collector-cache_data:/data

  traffic-collector:
    build:
      context: ./src
    container_name: traffic-collector
    environment:
      - MODE=traffic-collector
      - KAFKA_TOPIC=${TC_KAFKA_TOPIC}
      - KAFKA_AUTO_OFFSET_RESET=earliest
      - KAFKA_GROUP_ID=traffic-processor
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TC_CACHE_HOST=${TC_CACHE_HOST}
      - TC_CACHE_PORT=${TC_CACHE_PORT}
      - TC_CACHE_USER=${TC_CACHE_USER}
      - TC_CACHE_PASSWORD=${TC_CACHE_PASSWORD}
    depends_on:
      - kafka
      - traffic-collector-cache

volumes:
  postgres_data:
  tc-postgres_data: 
  plans-postgres_data:
  traffic-collector-cache_data:
